/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bcash;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URI;

/**
 *
 * @author APCL
 */
public class BKashMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form BKashMainFrame
     */
    public BKashMainFrame() {
        initComponents();
        windowProfile();
    }
    
    public void windowProfile() {
        Toolkit thekit = this.getToolkit();
        Dimension winSize = thekit.getScreenSize();
        this.setLocation(winSize.width / 4, winSize.height / 4);
        this.setTitle("bKash");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JButton();
        btnAgent = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblBrac = new javax.swing.JLabel();
        lblJanata = new javax.swing.JLabel();
        lblDutch = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblFareast = new javax.swing.JLabel();
        lblFirstCapital = new javax.swing.JLabel();
        lblWestern = new javax.swing.JLabel();
        lblEkhaney = new javax.swing.JLabel();
        lblBikroy = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        jLabel5.setText("jLabel5");

        jLabel4.setText("jLabel4");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("City Bank Ltd.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 51, 204));

        btnCustomer.setBackground(new java.awt.Color(51, 255, 255));
        btnCustomer.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(0, 0, 204));
        btnCustomer.setText("CUSTOMER");
        btnCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnAgent.setBackground(new java.awt.Color(0, 255, 255));
        btnAgent.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnAgent.setForeground(new java.awt.Color(51, 0, 153));
        btnAgent.setText("AGENT");
        btnAgent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentActionPerformed(evt);
            }
        });

        btnEmployee.setBackground(new java.awt.Color(51, 255, 204));
        btnEmployee.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(0, 102, 102));
        btnEmployee.setText("EMPLOYEE");
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 102));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 51));
        jPanel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel2.setLayout(null);

        lblBrac.setBackground(new java.awt.Color(255, 255, 255));
        lblBrac.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblBrac.setForeground(new java.awt.Color(0, 51, 204));
        lblBrac.setText("* BRAC Bank Ltd.");
        lblBrac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBrac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBracMouseClicked(evt);
            }
        });
        jPanel2.add(lblBrac);
        lblBrac.setBounds(40, 30, 150, 20);

        lblJanata.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblJanata.setForeground(new java.awt.Color(0, 0, 153));
        lblJanata.setText("* Janata Bank Ltd.");
        lblJanata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJanata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJanataMouseClicked(evt);
            }
        });
        jPanel2.add(lblJanata);
        lblJanata.setBounds(40, 60, 140, 20);

        lblDutch.setBackground(new java.awt.Color(204, 255, 255));
        lblDutch.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblDutch.setForeground(new java.awt.Color(204, 0, 153));
        lblDutch.setText("* Dutch Bangla Bank Ltd. ");
        lblDutch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDutch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDutchMouseClicked(evt);
            }
        });
        jPanel2.add(lblDutch);
        lblDutch.setBounds(40, 120, 180, 20);

        lblCity.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 51, 204));
        lblCity.setText("* City Bank Ltd.");
        lblCity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCityMouseClicked(evt);
            }
        });
        jPanel2.add(lblCity);
        lblCity.setBounds(40, 90, 130, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("---------------------");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 170, 150, 17);

        lblFareast.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblFareast.setForeground(new java.awt.Color(0, 0, 153));
        lblFareast.setText("# Fareast Finance & Investment Ltd.");
        lblFareast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFareast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFareastMouseClicked(evt);
            }
        });
        jPanel2.add(lblFareast);
        lblFareast.setBounds(40, 290, 250, 20);

        lblFirstCapital.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblFirstCapital.setForeground(new java.awt.Color(153, 0, 153));
        lblFirstCapital.setText("# First Capital Securities Ltd.");
        lblFirstCapital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFirstCapital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFirstCapitalMouseClicked(evt);
            }
        });
        jPanel2.add(lblFirstCapital);
        lblFirstCapital.setBounds(40, 320, 190, 17);

        lblWestern.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblWestern.setForeground(new java.awt.Color(153, 0, 0));
        lblWestern.setText("# Western Union Money Transfer");
        lblWestern.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblWestern.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWesternMouseClicked(evt);
            }
        });
        jPanel2.add(lblWestern);
        lblWestern.setBounds(40, 260, 230, 20);

        lblEkhaney.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblEkhaney.setForeground(new java.awt.Color(102, 0, 102));
        lblEkhaney.setText("# ekhaney . com");
        lblEkhaney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEkhaney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEkhaneyMouseClicked(evt);
            }
        });
        jPanel2.add(lblEkhaney);
        lblEkhaney.setBounds(40, 200, 140, 20);

        lblBikroy.setFont(new java.awt.Font("DaunPenh", 1, 22)); // NOI18N
        lblBikroy.setForeground(new java.awt.Color(0, 51, 102));
        lblBikroy.setText("# Bikroy.com");
        lblBikroy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBikroy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBikroyMouseClicked(evt);
            }
        });
        jPanel2.add(lblBikroy);
        lblBikroy.setBounds(40, 230, 120, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBracMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBracMouseClicked
            goWebBRAC();// TODO add your handling code here:
    }//GEN-LAST:event_lblBracMouseClicked

    private void lblJanataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJanataMouseClicked
            goWebJanata();// TODO add your handling code here:
    }//GEN-LAST:event_lblJanataMouseClicked

    private void lblCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCityMouseClicked
            goWebCity(); // TODO add your handling code here:
    }//GEN-LAST:event_lblCityMouseClicked

    private void lblDutchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDutchMouseClicked
               goWebDutchBangla(); // TODO add your handling code here:
    }//GEN-LAST:event_lblDutchMouseClicked

    private void lblEkhaneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEkhaneyMouseClicked
                goWebEkhaney(); // TODO add your handling code here:
    }//GEN-LAST:event_lblEkhaneyMouseClicked

    private void lblBikroyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBikroyMouseClicked
                goWebBikroy(); // TODO add your handling code here:
    }//GEN-LAST:event_lblBikroyMouseClicked

    private void lblWesternMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWesternMouseClicked
                goWebWesternUnion(); // TODO add your handling code here:
    }//GEN-LAST:event_lblWesternMouseClicked

    private void lblFareastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFareastMouseClicked
                goWebFareastFinance();// TODO add your handling code here:
    }//GEN-LAST:event_lblFareastMouseClicked

    private void lblFirstCapitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirstCapitalMouseClicked
                 goWebFirstcapital();// TODO add your handling code here:
    }//GEN-LAST:event_lblFirstCapitalMouseClicked

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentActionPerformed
        // TODO add your handling code here:
        AgentLoginFrame alf = new AgentLoginFrame();
        alf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgentActionPerformed

    public void goWebBRAC(){
        try {
            Desktop.getDesktop().browse(new URI("www.bracbank.com"));
        } catch (Exception e) {
        }
    }
    public void goWebJanata(){
        try {
            Desktop.getDesktop().browse(new URI("www.janatabank-bd.com"));
        } catch (Exception e) {
        }
    }
    public void goWebCity(){
        try {
            Desktop.getDesktop().browse(new URI("www.thecitybank.com"));
        } catch (Exception e) {
        }
    }
    public void goWebDutchBangla(){
        try {
            Desktop.getDesktop().browse(new URI("www.dutchbanglabank.com"));
        } catch (Exception e) {
        }
    }
    public void goWebEkhaney(){
        try {
            Desktop.getDesktop().browse(new URI("www.ekhanei.com"));
        } catch (Exception e) {
        }
    }
    public void goWebBikroy(){
        try {
            Desktop.getDesktop().browse(new URI("www.bikroy.com"));
        } catch (Exception e) {
        }
    }
    public void goWebWesternUnion(){
        try {
            Desktop.getDesktop().browse(new URI("www.westernunion.com"));
        } catch (Exception e) {
        }
    }
    public void goWebFareastFinance(){
        try {
            Desktop.getDesktop().browse(new URI("www.fareastfinance&investmentltd.com"));
        } catch (Exception e) {
        }
    }
    public void goWebFirstcapital(){
        try {
            Desktop.getDesktop().browse(new URI("www.firstcapitalsecuritiesltd.com"));
        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BKashMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BKashMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BKashMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BKashMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BKashMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgent;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBikroy;
    private javax.swing.JLabel lblBrac;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDutch;
    private javax.swing.JLabel lblEkhaney;
    private javax.swing.JLabel lblFareast;
    private javax.swing.JLabel lblFirstCapital;
    private javax.swing.JLabel lblJanata;
    private javax.swing.JLabel lblWestern;
    // End of variables declaration//GEN-END:variables
}
