/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bcash;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author apcl
 */
public class BuyAirtimeFrame extends javax.swing.JFrame {

    DataConnectionTemplate dbObj = new DataConnectionTemplate();
    String strMolibeOparetor, strMethod, strRequiredNo, strMoNum, strAmount, strPass;
    float amount;
    
    /**
     * Creates new form BuyAirtimeFrame
     */
    public BuyAirtimeFrame() {
        initComponents();
        windowProfile();
        openingWindow();
        inactiveField();
    }
    
    public void windowProfile(){
        Toolkit thekit = this.getToolkit();
        Dimension winSize = thekit.getScreenSize();
        
        this.setLocation(winSize.width/3, winSize.height/6);
        this.setTitle("bKash");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxMobileOper = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxPayMethod = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        cbxRequiredNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Back to Customer Homepage");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buy Aritime", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Select Mobile Operator :");

        cbxMobileOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Banglalink", "GP", "Robi", "Teletalk" }));
        cbxMobileOper.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMobileOperItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Payment Method : ");

        cbxPayMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Prepaid", "Postpaid" }));
        cbxPayMethod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPayMethodItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Enter Mobile No. : ");

        txtMobile.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Amount : ");

        txtAmount.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Password : ");

        txtPass.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Required No. : ");

        cbxRequiredNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Self", "Other" }));
        cbxRequiredNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxRequiredNoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxMobileOper, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxPayMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMobile)
                    .addComponent(txtAmount)
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(cbxRequiredNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxMobileOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxPayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxRequiredNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMobileOperItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMobileOperItemStateChanged
        // TODO add your handling code here:

        if (!cbxMobileOper.getSelectedItem().equals("Select")) {
            cbxPayMethod.setEnabled(true);
        } else if (cbxMobileOper.getSelectedItem().equals("Select")) {
            openingWindow();
        }

    }//GEN-LAST:event_cbxMobileOperItemStateChanged

    private void cbxPayMethodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPayMethodItemStateChanged
        if (!cbxPayMethod.getSelectedItem().equals("Select")) {
            cbxRequiredNo.setEnabled(true);
            
        } else {
            cbxRequiredNo.setSelectedIndex(0);
            cbxRequiredNo.setEnabled(false);
        }
    }//GEN-LAST:event_cbxPayMethodItemStateChanged

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyTyped
        // TODO add your handling code here:
        initalValues();
        char key =evt.getKeyChar();
        if (!(Character.isDigit(key) & (strMoNum.length() < 11))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMobileKeyTyped

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        // TODO add your handling code here:
        char key =evt.getKeyChar();
        if (!(Character.isDigit(key) || key == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAmountKeyTyped

    private void cbxRequiredNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxRequiredNoItemStateChanged
        // TODO add your handling code here:
        if (!(cbxRequiredNo.getSelectedItem().equals("Select"))) {
            activeField();
        } else if (cbxRequiredNo.getSelectedItem().equals("Select")) {
            inactiveField();
        }
        
        if (cbxRequiredNo.getSelectedItem().equals("Self")) {
            txtMobile.setEnabled(false);
        }else{
            txtMobile.setEnabled(true);
        }
    }//GEN-LAST:event_cbxRequiredNoItemStateChanged

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        doingTopup();
        cbxMobileOper.setSelectedIndex(0);
        clearField();
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyAirtimeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyAirtimeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyAirtimeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyAirtimeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyAirtimeFrame().setVisible(true);
            }
        });

    }

    public void openingWindow() {
        clearField();
        cbxPayMethod.setEnabled(false);
        cbxRequiredNo.setEnabled(false);
    }

    public void inactiveField() {
        txtMobile.setEditable(false);
        txtAmount.setEditable(false);
        txtPass.setEditable(false);
        btnSubmit.setEnabled(false);
    }

    public void activeField() {
        
        txtMobile.setEditable(true);
        txtAmount.setEditable(true);
        txtPass.setEditable(true);
        btnSubmit.setEnabled(true);
    }

    public void clearField() {
        cbxPayMethod.setSelectedIndex(0);
        cbxRequiredNo.setSelectedIndex(0);
        txtMobile.setText("");
        txtAmount.setText("");
        txtPass.setText("");
    }

    public void initalValues(){
        strMolibeOparetor = cbxMobileOper.getSelectedItem().toString();
        strMethod = cbxPayMethod.getSelectedItem().toString();
        strRequiredNo = cbxRequiredNo.getSelectedItem().toString();
        if (strRequiredNo.equals("Self")) {
            strMoNum = LoginFrame.getStrMobile();
        } else {
            strMoNum = txtMobile.getText();
        }
        strAmount = txtAmount.getText();
        strPass = txtPass.getText();
        
        try {
            amount = Float.valueOf(strAmount);
        } catch (NumberFormatException e) {
        }
    }
    
    public void doingTopup(){
        initalValues();
        dbObj.doConnection();
        if (LoginFrame.getStrMobile().equals(strMoNum)) {
            String stm = "update user_login_table set amount = amount - " + amount + 
                    ", topup = " + amount + " where u_id = '" + strMoNum + "';";
            int n = dbObj.modifyData(stm);
            if (n > 0) {
                String transStm = "insert into transaction_table(s_id,r_id,amount) values ('" + strMoNum + "', '" + strMoNum + "', " + amount + ");";
                int t = dbObj.modifyData(transStm);
                if (t > 0) {
                    JOptionPane.showMessageDialog(null, "Topup sucessfully");
                }                 
            } else {
                JOptionPane.showMessageDialog(null, "Your have no enough suffecent balance.");
            }
        } else {
            String stm1 = "update user_login_table set topup = " + amount + 
                    " where u_id = '" + strMoNum + "';";
            int n = dbObj.modifyData(stm1);
            if (n > 0) {
                String stm2 = "update user_login_table set amount = amount - " + amount + 
                    " where u_id = '" + LoginFrame.getStrMobile() + "' and amount > " + 
                        amount + ";";
                int m = dbObj.modifyData(stm2);
                if (m > 0) {
                    String transStm = "insert into transaction_table(s_id,r_id,amount) values ('" + LoginFrame.getStrMobile() + "', '" + strMoNum + "', " + amount + ");";
                    int t = dbObj.modifyData(transStm);
                    if (t > 0) {
                        JOptionPane.showMessageDialog(null, "Topup sucessfully");
                    } 
                } else {
                    JOptionPane.showMessageDialog(null, "Your have no enough suffecent balance.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "The bKask account invalid !!");
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbxMobileOper;
    private javax.swing.JComboBox<String> cbxPayMethod;
    private javax.swing.JComboBox<String> cbxRequiredNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
